# Generated by Django 3.2 on 2023-08-29 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('co_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('co_name', models.CharField(max_length=255, verbose_name='Nombre Empresa')),
                ('co_address', models.CharField(help_text='ej: calle siempre viva 1010', max_length=255, verbose_name='Dirección de la empresa')),
                ('co_latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitud')),
                ('co_longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitud')),
                ('co_logo', models.ImageField(blank=True, help_text=' Formatos .jpg|.png|.gif|.jpeg', null=True, upload_to='image/logo/', verbose_name='Logo Empresa')),
                ('co_active', models.CharField(choices=[('Y', 'SI'), ('N', 'NO')], default='Y', max_length=1, verbose_name='Activo')),
                ('comuna', models.ForeignKey(db_column='co_comuna_id', on_delete=django.db.models.deletion.PROTECT, to='account.comuna', verbose_name='Comuna')),
                ('pais', models.ForeignKey(db_column='co_pais_id', on_delete=django.db.models.deletion.PROTECT, to='account.pais', verbose_name='País')),
                ('region', models.ForeignKey(db_column='co_region_id', on_delete=django.db.models.deletion.PROTECT, to='account.region', verbose_name='Región')),
            ],
            options={
                'db_table': 'com_company',
                'ordering': ['co_id'],
            },
        ),
    ]
