# Generated by Django 3.2 on 2023-08-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230812_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreinventor',
            name='reinventor',
            field=models.ForeignKey(blank=True, db_column='ur_reinventor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='account.reinventor', verbose_name='Reinventor'),
        ),
    ]
